### ISSUE TITLE
Fails to load simple c# exe.

### ISSUE THREAD

**Issue by nerfirelia123** [CCob/SharpBlock#11]
I have a simple c# exe that is reflecting bytes in memory. I'd like to use this tool to crush avast/avg since they're protecting amsi. Not really sure what I'm doing wrong. I'm executing it through cmd using your example but sharpblock is always throwing an error, compiled it as is no changes. Like I know I don't understand the code too well but I think I'm understanding what the tool is supposed to do. Bro I must be doing something wrong, do I need to compile my exe a certain type of way?

**Comment by nerfirelia123** [comment]
![alt text](https://i.imgur.com/KjHjpEh.jpg)

This is a hello world form app in c# .net framework 4. I built sharpblock as x64.

**Comment by CCob** [comment]
Notepad is already loaded at 0x400000 (default base on x86) so your hello.ex can't live at the same address.  It therefore needs relocation to a different location, but your hello.exe has no relocation info compiled into it so it fails
