### ISSUE TITLE
Failed to create process nltest.exe with error 2

### ISSUE THREAD

**Issue by surajpkhetani** [CCob/SharpBlock#5]
Thanks for the amazing work. 
I was successfully able to run the nltest /dclist: command and a DLL to patch initially.

Tried after a few days but with a different beacon and now I get an error ``` Failed to create process nltest.exe with error 2 ``` This is the command i execute ```SharpBlock.exe -e nltest.exe -a /dclist: -n XYZ.dll```

Below is the response:
```
[*] Tasked beacon to run .NET program: SharpBlock.exe -e nltest.exe -a /dclist: -n XYZ.dll
[+] host called home, sent: 219777 bytes
[+] received output:
SharpBlock by @_EthicalChaos_
  DLL Blocking app for child processes x86_64 


[+] received output:
[+] in-proc amsi 0x00007ffe7a860000
[+] in-proc ntdll 0x00007ffe90580000
[!] Failed to create process nltest.exe with error 2
```

Any idea what can be corrected here?

**Comment by CCob** [comment]
Error 2 is file not found.  So I'm guessing it's referring to the path of nltest.exe.  You will most likely need to fully qualify the path to it.

**Comment by surajpkhetani** [comment]
Yes absolutely. I missed that. Thanks.
