### ISSUE TITLE
Exception 0x800000003

### ISSUE THREAD

**Issue by t3hbb** [CCob/SharpBlock#9]
It appears to be a non-fatal error but I'm getting similar errors on multiple machines.

Windows [Version 10.0.18363.1440]

```
SharpBlock by @_EthicalChaos_
  DLL Blocking app for child processes x86_64

[+] in-proc amsi 0x00007ffa54d10000
[+] in-proc ntdll 0x00007ffa73fa0000
[+] Launched process c:\windows\system32\cmd.exe with PID 204
Exception 0x80000003 occured at 0x7ffa74070f8c
        Parameter: 0x0
[+] Updated command line args with ""
Exception 0x80000003 occured at 0x7ffa74070f8c
        Parameter: 0x0
```

Windows [Version 10.0.19042.1083]

```
C:\Tools\SharpBlock\bin\x64\Release>SharpBlock.exe
SharpBlock by @_EthicalChaos_
  DLL Blocking app for child processes x86_64

[+] in-proc amsi 0x00007ffc654b0000
[+] in-proc ntdll 0x00007ffc7ff10000
[+] Launched process c:\windows\system32\cmd.exe with PID 18516
Exception 0x80000003 occured at 0x7ffc7ffe0770
        Parameter: 0x0
[+] Updated command line args with ""
Exception 0x80000003 occured at 0x7ffc7ffe0770
        Parameter: 0x0
```

Everything else appears to work fine in that cmd is actually running with that PID in the background, just I don't remember seeing those error messages last time I used SharpBlock.

0x7ffc7ffe0770 is an 0xCC (Int 3) in ntdll.dll which I believe is causing the exception: 

![image](https://user-images.githubusercontent.com/21687763/125096868-7291b000-e0cd-11eb-99ee-52b9e5cfc157.png)

Exception is raised here (line 967 Program.cs) : 

```C#

                                if (ExceptionDebugInfo.dwFirstChance == 0 && ExceptionDebugInfo.ExceptionRecord.ExceptionCode != WinAPI.EXCEPTION_SINGLE_STEP) {
                                    Console.WriteLine($"Exception 0x{ExceptionDebugInfo.ExceptionRecord.ExceptionCode:x} occured at 0x{ExceptionDebugInfo.ExceptionRecord.ExceptionAddress.ToInt64():x}");
                                    for(int idx=0; idx< ExceptionDebugInfo.ExceptionRecord.NumberParameters; ++idx ) {
                                        Console.WriteLine($"\tParameter: 0x{ExceptionDebugInfo.ExceptionRecord.ExceptionInformation[idx]}");
                                    }      
```                   

Thank you for a really great tool, anything I can do to help troubleshoot, please let me know

**Comment by CCob** [comment]
It's just additional logging added around exceptions raised within the child process, shouldn't affect the behaviour.  I should probably add a check for WinAPI.EXCEPTION_BREAKPOINT in addition to WinAPI.EXCEPTION_SINGLE_STEP and ignore that type of exception. 

The main reason for the log message is an additional debugging aid in cases where the child process crashes due to unhandled exceptions.

**Comment by t3hbb** [comment]
Thanks for the feedback - closing as not a bug.
